deploy:
  provider: heroku
  api_key:
    secure: 
  app:
    master: main

language: node_js
node_js:
  - 16.14.2
cache:
  directories:
  - node_modules
script:
  - npm run lint
  - npm run cypress
  - npm run build
env:
  global:
  - NEXT_PUBLIC_GRAPHCMS_ENDPOINT = 'https://api-eu-west-2.graphcms.com/v2/cl1h8r7ux53ok01xf5x7292n2/master'
  - GRAPHCMS_TOKEN = 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImdjbXMtbWFpbi1wcm9kdWN0aW9uIn0.eyJ2ZXJzaW9uIjozLCJpYXQiOjE2NDkwNzkxMjcsImF1ZCI6WyJodHRwczovL2FwaS1ldS13ZXN0LTIuZ3JhcGhjbXMuY29tL3YyL2NsMWg4cjd1eDUzb2swMXhmNXg3MjkybjIvbWFzdGVyIiwiaHR0cHM6Ly9tYW5hZ2VtZW50LW5leHQuZ3JhcGhjbXMuY29tIl0sImlzcyI6Imh0dHBzOi8vbWFuYWdlbWVudC5ncmFwaGNtcy5jb20vIiwic3ViIjoiMjdhNmMwMGUtYTRmYS00M2FkLTk1YzctYmYwZGU2YjkwZjY5IiwianRpIjoiY2wxa3I0dTM3N285NTAxeGlnZXZsaDIyZSJ9.b_RguLZ-jo-V2MGRveSdW_6p5Pim7AEG2HdAnLkZktFKPc5qnJYtxHjQznz37YUnsD222lxMwmvwxgWDg7cfsMZrKwKPxm7olQ1J3oUxtPAQTZASWhQvG4AydNNNHOCHHW0H-jIjl5_LeiL4Lsetvl85AogVd-bSVfuvGzLOlHSGppMYhQi79T6wpvVRd0pmnXeaccfU_L6-d5bAbgS8iSbc4t9uDKBJer0f97Umz9BvQHIMV-K_HWSfFNjuuEmXm1R8pCDV_ump3zZGNJiLlU0pGTLclTWNO_nEGwJwivrIv65dxW_rDhTwmkYL3FYpiinbVFS3OcUNsYZjUTy5xtfT5Z0g5Cbsm-AYFJz8sb-AZDWucPR6DrP5m95cIo9sfd9Ga0EcC5aV4NGa6J9IRGtnRlj0_cM6nOp4a2fLxxBQkyb8exZ_vYigD5FcINomGJ5nKyjqRYpc4g8ZkMhP0hvICOJCvx4kwvbZZY48EkkiGlJJeo0arCWwbYrZ1fQS6ylfaLCIXw7VIO_LSFx4PEjB79kV52aeaPROs7Bwlm11jtb1DDkoZYfcKsS0Zmrtws10Itb3kv_zoSO9fmvL5TUrNBKBz5b-H-H-qLj45wF23VzxfyVnS32QDo946V5BX0f3VzWUNMCxwmj3mhLm0FOTO95drjLUmkTGCzu-p-U'
after_success:
- export REPO=BlogApp/client-nextjs
